[dotfiles]
"~/.config/bat" = { source = "../work/.config/bat" }
"~/.config/bottom" = { source = "../work/.config/bottom" }
"~/.config/eza" = { source = "../work/.config/eza" }
"~/.bashrc/fzf" = { block = '''
  export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
    --highlight-line \
    --info=inline-right \
    --ansi \
    --layout=reverse \
    --border=none \
    --color=bg+:#283457 \
    --color=bg:#16161e \
    --color=border:#27a1b9 \
    --color=fg:#c0caf5 \
    --color=gutter:#16161e \
    --color=header:#ff9e64 \
    --color=hl+:#2ac3de \
    --color=hl:#2ac3de \
    --color=info:#545c7e \
    --color=marker:#ff007c \
    --color=pointer:#ff007c \
    --color=prompt:#2ac3de \
    --color=query:#c0caf5:regular \
    --color=scrollbar:#27a1b9 \
    --color=separator:#ff9e64 \
    --color=spinner:#ff007c \
  "
  ''' }
"~/.config/starship.toml" = { source = "../work/.config/starship.toml" }
"~/.config/fish/config.fish/fzf" = { block = '''
  set -Ux FZF_DEFAULT_OPTS "\
   --highlight-line \
   --info=inline-right \
   --ansi \
   --layout=reverse \
   --border=none \
   --color=bg+:#283457 \
   --color=bg:#16161e \
   --color=border:#27a1b9 \
   --color=fg:#c0caf5 \
   --color=gutter:#16161e \
   --color=header:#ff9e64 \
   --color=hl+:#2ac3de \
   --color=hl:#2ac3de \
   --color=info:#545c7e \
   --color=marker:#ff007c \
   --color=pointer:#ff007c \
   --color=prompt:#2ac3de \
   --color=query:#c0caf5:regular \
   --color=scrollbar:#27a1b9 \
   --color=separator:#ff9e64 \
   --color=spinner:#ff007c \
  "
  ''' }
"~/.config/fish/config.fish/tokyonight" = { block = '''
  if status is-interactive
    fish_config theme choose "tokyonight_night"
  end
  ''' }
"~/.config/fish/themes" = { source = "../work/.config/fish/themes" }
"~/.config/yazi" = { source = "../work/.config/yazi" }
