[tools]
"aqua:iffse/pay-respects" = "latest"
7zip = "latest"
bat = "latest"
biome = "latest"
bottom = "latest"
cargo-binstall = "latest"
eza = "latest"
fd = "latest"
ffmpeg = "latest"
fzf = "latest"
ghq = "latest"
github-cli = "latest"
imagemagick = "latest"
java = "latest"
jq = "latest"
navi = "latest"
node = "latest"
poppler = "latest"
ripgrep = "latest"
rust = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
stylua = "latest"
tombi = "latest"
topgrade = "latest"
ty = "latest"
usage = "latest"
uv = "latest"
yazi = "latest"
zoxide = "latest"
