[tools]
"cargo:tex-fmt" = "latest"
"github:A2-ai/rv" = "latest"
"pipx:radian" = "latest"

[bootstrap.packages]
"pacman:7zip" = "latest"
"pacman:adw-gtk-theme" = "latest"
"pacman:biber" = "latest"
"pacman:bitwarden" = "latest"
"pacman:blender" = "latest"
"pacman:bottles" = "latest"
"pacman:bpftune-git" = "latest"
"pacman:cachyos-gaming-applications" = "latest"
"pacman:cachyos-gaming-meta" = "latest"
"pacman:cava" = "latest"
"pacman:chromium" = "latest"
"pacman:clang" = "latest"
"pacman:cmake" = "latest"
"pacman:cups-pk-helper" = "latest"
"pacman:fastfetch" = "latest"
"pacman:fcitx5" = "latest"
"pacman:fcitx5-configtool" = "latest"
"pacman:fcitx5-gtk" = "latest"
"pacman:fcitx5-lua" = "latest"
"pacman:fcitx5-mozc-ut" = "latest"
"pacman:fcitx5-qt" = "latest"
"pacman:fish" = "latest"
"pacman:frameworkintegration" = "latest"
"pacman:gcc-fortran" = "latest"
"pacman:ghostty" = "latest"
"pacman:gimp" = "latest"
"pacman:gnome-disk-utility" = "latest"
"pacman:gvfs" = "latest"
"pacman:inkscape" = "latest"
"pacman:inter-font" = "latest"
"pacman:kdeconnect" = "latest"
"pacman:kimageformats" = "latest"
"pacman:libreoffice-fresh" = "latest"
"pacman:libreoffice-fresh-ja" = "latest"
"pacman:linux-cachyos-rc" = "latest"
"pacman:neovim" = "latest"
"pacman:ntfs-3g" = "latest"
"pacman:nwg-look" = "latest"
"pacman:otf-stix" = "latest"
"pacman:paru" = "latest"
"pacman:pavucontrol" = "latest"
"pacman:poppler" = "latest"
"pacman:proton-cachyos-native" = "latest"
"pacman:proton-cachyos-slr" = "latest"
"pacman:qalculate-gtk" = "latest"
"pacman:r" = "latest"
"pacman:rate-mirrors" = "latest"
"pacman:sl" = "latest"
"pacman:tabby-bin" = "latest"
"pacman:texlive" = "latest"
"pacman:texlive-lang" = "latest"
"pacman:thunar" = "latest"
"pacman:thunar-archive-plugin" = "latest"
"pacman:ttf-fira-code" = "latest"
"pacman:unityhub" = "latest"
"pacman:vivaldi" = "latest"
"pacman:vlc" = "latest"
"pacman:waydroid" = "latest"
"pacman:waydroid-helper" = "latest"
"pacman:xarchiver" = "latest"
"pacman:xed" = "latest"
"pacman:xorg-xhost" = "latest"
"pacman:xreader" = "latest"
"pacman:xviewer" = "latest"
"pacman:zathura-pdf-mupdf" = "latest"
"pacman:zed" = "latest"
"pacman:zoom" = "latest"
"aur:catppuccin-fcitx5-git" = "latest"
"aur:darkly" = "latest"
"aur:fastfetch-theme-manager" = "latest"
"aur:osu-lazer-bin" = "latest"
"aur:qtengine" = "latest"
"aur:tparted-bin" = "latest"
"aur:ttf-hackgen" = "latest"
