[shell_alias]
r = "radian"
mirror-update = "sudo cachyos-rate-mirrors && rate-mirrors chaotic-aur | sudo tee /etc/pacman.d/chaotic-mirrorlist"
miseboot = "mise -E home bootstrap"

[env]
EDITOR = "nvim"
GTK_THEME = "adw-gtk3"
PROTON_ENABLE_HDR = 1
PROTON_ENABLE_WAYLAND = 1
PROTON_NO_WM_DECORATION = 1
PROTON_USE_NTSYNC = 1
QT_IM_MODULE = "fcitx"
QT_QPA_PLATFORM = "wayland"
QT_QPA_PLATFORMTHEME = "qtengine"
QT_QPA_PLATFORMTHEME_QT6 = "qtengine"
QT_PLUGIN_PATH = "/usr/lib/qt5/plugins/"
TERMINAL = "ghostty"
VISUAL = "nvim"
XCURSOR_SIZE = "24"
XCURSOR_THEME = "Colloid-dark Cursors"
XDG_SESSION_TYPE = "wayland"
XMODIFIERS = "@im=fcitx"

[bootstrap.linux.firewall]
backend = "auto"
state = "enabled"

[[bootstrap.linux.firewall.rules]]
name = "kde-connect-tcp"
port = "1714-1764"
protocol = "tcp"
action = "allow"

[[bootstrap.linux.firewall.rules]]
name = "kde-connect-udp"
port = "1714-1764"
protocol = "udp"
action = "allow"
