[bootstrap.hooks.post-tools]
run = [
  "mise exec cargo:pez -- pez install --force",
  "mise exec bat -- bat cache --build",
]

[bootstrap.hooks.final]
run = [
  "mise bootstrap: Completed!",
]
