[bootstrap.hooks.pre-packages]
run = [
  '''pwsh -NoProfile -Command "Start-Process pwsh -Verb RunAs -ArgumentList '-NoProfile','-Command','sudo config --enable normal'"''',
  '''powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Import-Module Microsoft.PowerShell.Archive; & ([scriptblock]::Create((Invoke-RestMethod 'https://debloat.raphi.re/'))) -CLI -Config (Join-Path $HOME '.config\Win11Debloat\Win11Debloat-Config.json')"''',
]

[bootstrap.hooks.post-packages]
run = [
  '''pwsh -NoProfile -Command "Install-Module -Name PSWindowsUpdate -Force -Confirm:$false"''',
]

[bootstrap.hooks.post-tools]
run = [
  "mise exec topgrade -- topgrade --only system winget microsoft_store powershell",
]
